In [1]:
import numpy as np

berfungsi sebagai library untuk untuk mengolah operasi matematika 

In [2]:
Array = np.array([[19,141,86,70],
                 [100,148,85,251],
                 [7,75,173,173],
                 [246,165,8,221],])

berfungsi untuk membuat array yang akan diolah

In [3]:
low1 = [0.7,0.7]
high1 = [-0.7,0.7]

berfungsi untuk membuat array kernel low dan high dari soal A

In [4]:
low2 = [-0.1,0.2,0.8,0.4]
high2 = [-0.4,0.8,-0.2,-0.1]

berfungsi untuk membuat array kernel low dan high dari soal B

In [5]:
low3 = [0.03,-0.08,-0.1,0.45,0.8,0.33]
high3 = [-0.33,0.81,-0.46,-0.14,0.09,0.04]

berfungsi untuk membuat array kernel low dan high dari soal C

In [6]:
low4 = [-0.01,0.03,0.03,-0.19,0.02,0.63,0.71,0.23]
high4 = [-0.23,0.71,-0.63,-0.03,0.19,0.03,-0.03,-0.01]

berfungsi untuk membuat array kernel low dan high dari soal D

In [7]:
def padding (data,bnyk):
    pad1=np.pad(data,(0,bnyk),'constant')
    return pad1

fungsi di atas berfungsi untuk menambahkan padding untuk pengolahan konvolusi yang akan dilakukan, padding yang akan dibuat sesuai dengan kebutuhan yang dibutuhkan. Pada kode di atas merupakan sebuah library yang dari numpy yang di sediakan untuk menambah padding dimana "(0,bnyk)" bnyk di sini padding sesuai dengan kebutuhan yang di butuhkan.

In [8]:
def mencarih0(pad, kernel):
    zeros = np.zeros([4,4])
    for v in range (len(zeros)):
        for w in range (len(zeros)):
            for i in range(len(kernel)):
                zeros[v][w] += (kernel[i]*pad[v][w+i])
    return zeros

fungsi di atas berfungsi untuk mencari nilai pada konvolusi ke 0 atau h0, pada fungsi ini akan diolah data sesuai dengan kebutuhan yang akan diolah, pada data yang akan dikirim adalah data yang sudah diberikan padding untuk sebagai variable bantu, yang akan dikirim kedua adalah kernel yang akan diolah, entah itu kernel low atau kernel high yang di butuhkan. setelah di kirim maka akan diproses oleh program, kemudian akan di tentukan index pusat yang dimana index akan diisikan dengan data hasil kali antar data baris arraynya dengan kernelnya. kemudian di lakukan sampai semua index sudah sebagai pusat pengolahan dan mendapatkan semua data.

In [9]:
def seleckl (data):
    tmp=np.zeros((4,2))
    for v in range (4):
        for w in range (2):
            tmp[v,w]=data[v,w*2]
    return tmp

pada fungsi di atas akan diolah data hasil konvolusi yang, pengolah di sini akan menyeleksi kolom yang akan diambil, kolom yang akan diambil adalah kolom yang bernilai genap, sehingga menghasilkan matriks 4x2.

In [10]:
def padbawah (data):
    pad2=np.pad(data,(0,4),'constant')
    return pad2

In [11]:
def transpos (kernel):
    zh=np.zeros((len(kernel),1))
    for i in range (len(kernel)):
        for j in range (1):
            zh[i][j]=kernel[i]
    return zh

fungsi di atas befungsi sebagai pengolah transpose dari data atau array kernel sesuai dengan kebutuhan, yang dimana yang semula baris menjadi kolom, yang semula kolom menjadi baris.

In [12]:
def mencarih1(kernel,pad):
    tmp1=np.zeros((4,2))
    for v in range (4):
        for w in range (2):
            for j in range(len(kernel)):
                tmp1[v][w] += (kernel[j]*pad[j+v][w])
    return tmp1

fungsi di atas berfungsi untuk mencari nilai pada konvolusi ke 1 atau h1, pada fungsi ini akan diolah data sesuai dengan kebutuhan yang akan diolah, pada data di sini yang akan dikirim adalah data yang sudah diberikan sudah dikonvolusi h0 dan sudah diberikan padding sesuai dengan kebutuhan untuk sebagai veriable bantu yang akan dikirim kedua adalah kernel yang akan diolah, yang mana adalah kernel yang sudah ditranspose, sesuai dengan kebutuhan low atau high. setelah dikirim maka akan di proses oleh program, kemudian akan di tentukan index pusat yang dimana index ini akan diisikan dengan data hasil kali antar data kolom arraynya dengan kernelnya. kemudian dilakukan sampai semua index sudah sebagai pusat pengolahan dan mendapatklan semua data.

In [13]:
def selecbr(data):
    tmp2=np.zeros((2,2))
    for v in range (2):
        for w in range (2):
            tmp2[v,w]=data[v*2,w]
    return tmp2

pada fungsi di atas akan diolah data hasil konvolusi yang, pengolah disini akan menyeleksi baris yang akan diambil, baris yang akan diambil adalah kolom yang bernilai genap, sehingga menghasilkan matriks 2x2.

In [14]:
def finis(ll,hl,lh,hh):
    b1=np.concatenate((ll,hl),axis=1)
    b2=np.concatenate((lh,hh),axis=1)
    return np.concatenate((b1,b2),axis=0)

fungsi di atas berfungsi untuk menggabungkan semua LL,LH,HL,LL yang sudah di hitung dengan fungsi library numpy "concatenate"

## Jurnal 2

In [15]:
pad=padding(Array,4)
kv0=mencarih0(pad, low2)
pad_bw=seleckl(kv0)
hasilT=transpos(low2)
pad2=padding(pad_bw,4)
data=mencarih1(hasilT,pad2)
LL2=selecbr(data)
print (LL2)

[[244.09  39.  ]
 [ -1.55   6.95]]


pada code di atas adalah untuk menghitung LL terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagi varible bantu dengan fungsi "padding" dan kemudia hasil padding dan hasil transpos di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di varibel LL

In [16]:
pad=padding(Array,4)
kv0=mencarih0(pad, high2)
pad_bw=seleckl(kv0)
hasilT=transpos(low2)
pad2=padding(pad_bw,4)
data=mencarih1(hasilT,pad2)
HL2=selecbr(data)
print (HL2)

[[  7.36 156.  ]
 [  1.45  27.8 ]]


pada code di atas adalah untuk menghitung HL terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspost kernel yang akan dikirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpose di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di varibel HL.

In [17]:
kv0=mencarih0(pad, low2)
pad_bw=seleckl(kv0)
hasilT=transpos(high2)
pad2=padding(pad_bw,4)
data=mencarih1(hasilT,pad2)
LH2=selecbr(data)
print (LH2)

[[46.46 23.4 ]
 [-6.2  27.8 ]]


pada code di atas adalah untuk menghitung LH terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpos di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di varibel LH.

In [18]:
kv0=mencarih0(pad, high2)
pad_bw=seleckl(kv0)
hasilT=transpos(high2)
pad2=padding(pad_bw,4)
data=mencarih1(hasilT,pad2)
HH2=selecbr(data)
print (HH2)

[[ -5.41  93.6 ]
 [  5.8  111.2 ]]


In [19]:
finis(LL2,HL2,LH2,HH2)

array([[244.09,  39.  ,   7.36, 156.  ],
       [ -1.55,   6.95,   1.45,  27.8 ],
       [ 46.46,  23.4 ,  -5.41,  93.6 ],
       [ -6.2 ,  27.8 ,   5.8 , 111.2 ]])

code di atas berfungsi untuk menyatukan data yang LL,HL,LH,HH yang sudah di dapatkan menjadi 1 buah matriks yang utuh sehingga menghasilkan matriks 4x4 seperti gambar di atas, adapun bentuk data itu digabungkan sebagai berikut
### matrik 
### LL || HL
### ---------
### LH || HH

## Jurnal 1

In [20]:
pad=padding(Array,1)
kv0=mencarih0( pad, low1)
pad_bw=seleckl(kv0)
hasilT=transpos(low1)
pad2=padding(pad_bw,1)
data=mencarih1(hasilT,pad2)
LL1=selecbr(data)
print (LL1)

[[199.92 241.08]
 [241.57 281.75]]


pada code di atas adalah untuk menghitung LL terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan dikirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpose diolah dengan fungsi konvolusi 1 "mencarih1" setelah itu baru di seleksi baris matriknya setelah itu ditampung di variabel LL

In [21]:
kv0=mencarih0( pad, high1)
pad_bw=seleckl(kv0)
hasilT=transpos(low1)
pad2=padding(pad_bw,1)
data=mencarih1(hasilT,pad2)
HL1=selecbr(data)
print (HL1)

[[ 83.3   73.5 ]
 [ -6.37 104.37]]


pada code di atas untuk menghitung HL terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagi variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpose diolah dengan fungsi konvolusi 1 "mencarih1" setelah itu baru di seleksi baris matriknya setelah itu ditampung di variabel HL

In [22]:
kv0=mencarih0( pad, low1)
pad_bw=seleckl(kv0)
hasilT=transpos(high1)
pad2=padding(pad_bw,1)
data=mencarih1(hasilT,pad2)
LH1=selecbr(data)
print (LH1)

[[ 43.12  88.2 ]
 [161.21 -57.33]]


pada code di atas untuk menghitung LH Terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagi varible bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpose diolah dengan fungsi konvolusi 1 "mencarih1" setelah itu baru di seleksi baris matriknya setelah itu ditampung di varibel LH

In [23]:
kv0=mencarih0( pad, high1)
pad_bw=seleckl(kv0)
hasilT=transpos(high1)
pad2=padding(pad_bw,1)
data=mencarih1(hasilT,pad2)
HH1=selecbr(data)
print (HH1)

[[-36.26  89.18]
 [-73.01 104.37]]


In [24]:
finis (LL1,HL1,LH1,HH1)

array([[199.92, 241.08,  83.3 ,  73.5 ],
       [241.57, 281.75,  -6.37, 104.37],
       [ 43.12,  88.2 , -36.26,  89.18],
       [161.21, -57.33, -73.01, 104.37]])

code di atas berfungsi untuk menyatukan data yang LL,HL,LH,HH yang sudah di dapatkan menjadi 1 buah matrik yang utuh sehingga menghasilkan matirk 4x4 seperti gambar di atas, adapun bentuk data itu di gabungkan sebagai berikut.
### matrik 
### LL || HL
### ---------
### LH || HH

## Jurnal3

In [25]:
pad=padding(Array,9)
kv0=mencarih0( pad, low3)
pad_bw=seleckl(kv0)
hasilT=transpos(low3)
pad2=padding(pad_bw,9)
data=mencarih1(hasilT,pad2)
LL3=selecbr(data)
print (LL3)

[[29.0144 -5.6712]
 [-5.7836  1.1357]]


pada code di atas untuk menghitung LL terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagi varible bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpose diolah dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu ditampung di varibel LL

In [26]:
kv0=mencarih0( pad, high3)
pad_bw=seleckl(kv0)
hasilT=transpos(low3)
pad2=padding(pad_bw,9)
data=mencarih1(hasilT,pad2)
HL3=selecbr(data)
print (HL3)

[[ 13.3147  57.8913]
 [ -2.7888 -11.6184]]


pada code di atas untuk menghitung HL Terlebih dahulu yang mana di atas pertama akan mencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpos diolah dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu ditampung di variabel HL

In [27]:
kv0=mencarih0( pad, low3)
pad_bw=seleckl(kv0)
hasilT=transpos(high3)
pad2=padding(pad_bw,9)
data=mencarih1(hasilT,pad2)
LH3=selecbr(data)
print (LH3)

[[ 35.2356  -6.7821]
 [ 57.1215 -11.2719]]


pada code di atas untuk menghitung LH Terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspos kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudian hasil padding dan hasil transpos diolah dengan fungsi konvolusi 1 "mencarih1" setelah itu baru di seleksi baris matriknya setelah itu ditampung di varibel LH

In [28]:
kv0=mencarih0( pad, high3)
pad_bw=seleckl(kv0)
hasilT=transpos(high3)
pad2=padding(pad_bw,9)
data=mencarih1(hasilT,pad2)
HH3=selecbr(data)
print (HH3)

[[  9.2736  69.7248]
 [ 29.4273 115.4565]]


In [29]:
finis (LL3,HL3,LH3,HH3)

array([[ 29.0144,  -5.6712,  13.3147,  57.8913],
       [ -5.7836,   1.1357,  -2.7888, -11.6184],
       [ 35.2356,  -6.7821,   9.2736,  69.7248],
       [ 57.1215, -11.2719,  29.4273, 115.4565]])

code di atas berfungsi untuk menyatukan data yang LL,HL,LH,HH yang sudah di dapatkan menjadi 1 buah matrik yang utuh sehingga menghasilkan matirk 4x4 seperti gambar di atas, adapun bentuk data itu di gabungkan sebagai berikut.
### matrik 
### LL || HL
### ---------
### LH || HH

## Jurnal 4

In [30]:
pad=padding(Array,11)
kv0=mencarih0( pad, low4)
pad_bw=seleckl(kv0)
hasilT=transpos(low4)
pad2=padding(pad_bw,11)
data=mencarih1(hasilT,pad2)
LL4=selecbr(data)
print (LL4)

[[ 5.5102 -0.9527]
 [-0.9228  0.1619]]


pada code di atas untuk menghitung LL Terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudia hasil padding dan hasil transpos di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di variabel LL

In [31]:
kv0=mencarih0( pad, high4)
pad_bw=seleckl(kv0)
hasilT=transpos(low4)
pad2=padding(pad_bw,11)
data=mencarih1(hasilT,pad2)
HL4=selecbr(data)
print (HL4)

[[-10.9318 -22.5115]
 [  2.0924   3.8217]]


pada code di atas untuk menghitung HL Terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagi varible bantu dengan fungsi "padding" dan kemudia hasil padding dan hasil transpos di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di varibel HL

In [32]:
kv0=mencarih0( pad, low4)
pad_bw=seleckl(kv0)
hasilT=transpos(high4)
pad2=padding(pad_bw,11)
data=mencarih1(hasilT,pad2)
LH4=selecbr(data)
print (LH4)

[[-10.8278   2.0813]
 [-22.0096   3.8547]]


pada code di atas untuk menghitung LH Terlebih dahulu yang mana di atas pertama akan nencari konvolusi 0 dengan fungsi "mencarih0" kemudian menyeleksi data hasil konvolusi 0 yang genap saja dengan fungsi "seleckl" kemudian mentranspose kernel yang akan di kirim dengan fungsi "transpos" kemudian hasil seleksi tadi di berikan padding sebagai variable bantu dengan fungsi "padding" dan kemudia hasil padding dan hasil transpos di oleh dengan fungsi konvolusi 1 "mencarih1" stelah itu baru di seleksi baris matriknya setelah itu di tampung di varibel LH

In [33]:
kv0=mencarih0( pad, high4)
pad_bw=seleckl(kv0)
hasilT=transpos(high4)
pad2=padding(pad_bw,11)
data=mencarih1(hasilT,pad2)
HH4=selecbr(data)
print (HH4)

[[43.7674 48.7997]
 [49.1032 91.0005]]


In [34]:
finis (LL4,HL4,LH4,HH4)

array([[  5.5102,  -0.9527, -10.9318, -22.5115],
       [ -0.9228,   0.1619,   2.0924,   3.8217],
       [-10.8278,   2.0813,  43.7674,  48.7997],
       [-22.0096,   3.8547,  49.1032,  91.0005]])

code di atas berfungsi untuk menyatukan data yang LL,HL,LH,HH yang sudah di dapatkan menjadi 1 buah matrik yang utuh sehingga menghasilkan matirk 4x4 seperti gambar di atas, adapun bentuk data itu di gabungkan sebagai berikut.
### matrik 
### LL || HL
### ---------
### LH || HH