In [146]:
import numpy as np

Code di atas berfungsi untuk memanggil import numpy yang diinisialkan dengan np.

In [147]:
c=np.array([[4,7,1],[2,1,3],[3,0,0]])
a=np.zeros(c.shape)
print(c)
print(a)

[[4 7 1]
 [2 1 3]
 [3 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Code "c=np.array([[4,7,1],[2,1,3],[3,0,0]])" digunakan untuk menyimpan nilai matriks dengan ordo 3x3 yang nilainya telah ditentukan dan disimpan dalam variabel c. Code "a=np.zeros(c.shape)" digunkan untuk membuat matriks dengan ordo yang sama dengan variabel c dan memiliki nilai 0 semua. Perintah print berfungsi untuk menampilkan nilai dari variabel c dan a.

In [148]:
r=np.deg2rad(90)
cosR=(np.floor(np.cos(r)))
sinR=(np.floor(np.sin(r)))
for x in range (3):
    for y in range (3):
        x2=cosR*(x-1)-sinR*(y-1)+1
        y2=sinR*(x-1)+cosR*(y-1)+1
        a[int(x2)][int(y2)]=c[x][y]
print(a)

[[1. 3. 0.]
 [7. 1. 0.]
 [4. 2. 3.]]


Code "r=np.deg2rad(90)" berfungsi untuk mengubah nilai derajat 90 menjadi radian. Code "cosR=(np.floor(np.cos(r)))" berfungsi untuk mengambil nilai cos dari radian dan nilainya dibulatkan ke bawah. Code "sinR=(np.floor(np.sin(r)))" berfungsi untuk mengambil nilai sin dari radian dan nilainya dibulatkan ke bawah. Code "for x in range (3):" dan "for y in range (3):" digunakan untuk membuat perulangan matriks dengan ordo yang ditentukan. Code "x2=cosR*(x-1)-sinR*(y-1)+1", "y2=sinR*(x-1)+cosR*(y-1)+1", dan "a[int(x2)][int(y2)]=c[x][y]" merupakan code yang digunakan untuk menghitung rotasi dari matriks c. Perintah print digunakan untuk menampilkan hasil rotasi matriks c.

In [149]:
for x in range (3):
    for y in range (3):
        x2=x+1
        y2=y+1
        if x2<3:
            if y2<3:
                a[x2][y2]=c[x][y]
print (a)

[[1. 3. 0.]
 [7. 4. 7.]
 [4. 2. 1.]]


Code "for x in range (3):" dan "for y in range (3):" digunakan untuk membuat perulangan matriks dengan ordo yang ditentukan. Code "x2=x+1" dan "y2=y+1" digunakan untuk menyatakan bahwa pergeseran sumbu x dan sumbu y masing-masing ditambahkan dengan 1. Code "if x2<3:" dan "if y2<3:" merupakan sebuah kondisi yang dimana jika kondisi itu sesuai, maka akan melanjutkan ke proses selanjutnya yaitu "a[x2][y2]=c[x][y]" yang dimana a merupakan variabel hasil translasi. Perintah print digunakan untuk menampilkan hasil dari translasi yang terdapat dalam variabel a.

In [150]:
d=np.zeros((6,6))
for x in range (3):
    for y in range (3):
        for i in range (2):
            for j in range (2):
                d[x*2][y*2]=c[x][y]
                d[x*2][y*2+1]=c[x][y]
                d[x*2+1][y*2]=c[x][y]
                d[x*2+1][y*2+1]=c[x][y]
print(d)

[[4. 4. 7. 7. 1. 1.]
 [4. 4. 7. 7. 1. 1.]
 [2. 2. 1. 1. 3. 3.]
 [2. 2. 1. 1. 3. 3.]
 [3. 3. 0. 0. 0. 0.]
 [3. 3. 0. 0. 0. 0.]]


Code "d=np.zeros((6,6))" digunkan untuk membuat matriks dengan ordo 6x6 dan memiliki nilai 0 semua. Code "for x in range (3):" dan "for y in range (3):" digunakan untuk membuat perulangan matriks dengan ordo yang ditentukan. Code "for i in range (2):" dan "for j in range (2):" digunakan untuk membuat perulangan matriks dengan ordo yang ditentukan, dimana kedua code ini merupakan perulangan yang digunakan untuk proses dilatasi di dalam matriks 3x3 yang sebelumnya dibuat. Code "d[x*2][y*2]=c[x][y]", "d[x*2][y*2+1]=c[x][y]", "d[x*2+1][y*2]=c[x][y]", dan "d[x*2+1][y*2+1]=c[x][y]" merupakan penyalinan setiap pixel sebanyak 4 kali, jadi cita 3x3 menjadi 6x6 pixel. Perintah print digunakan untuk menampilkan hasil dari dilatasi.

In [151]:
m=2
n=2
for x in range (3):
    for y in range (3):
        a[x][y]=c[x][m-y]
print(a)

[[1. 7. 4.]
 [3. 1. 2.]
 [0. 0. 3.]]


Code "m=2" dan "n=2" digunakan untuk memberikan nilai variabel m dan n dengan nilai 2. Code "for x in range (3):" dan "for y in range (3):" digunakan untuk membuat perulangan matriks dengan ordo yang ditentukan. Code "a[x][y]=c[x][m-y]" digunakan untuk proses pencerminan terhadap sumbu x. Perintah print digunakan untuk menampilkan nilai pencerminan matriks c.